apiVersion: v1

kind: Service

metadata:
  name: react


spec:

  type: NodePort

  selector:

    app: react

  ports:

    - port: 3000

      protocol: TCP

      targetPort: 3000

      nodePort: 30010
